//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsTrackingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Haber
    {
        public int Id { get; set; }
        public int KategoriId { get; set; }
        public string HaberBaslik { get; set; }
        public string HaberIcerik { get; set; }
    
        public virtual Tbl_Kategori Tbl_Kategori { get; set; }
    }
}
